theme: jekyll-theme-minimal
title: Kevin Simmt
description: >
  PhD Candidate <br />
  Department of Political Science <br />
  The Ohio State University <br/ >
  mailto:simmt1@osu.edu
logo: /simmt.JPG
google_analytics: []
