theme: jekyll-theme-minimal
title: Kevin Simmt
description: PhD Candidate The Ohio State University Department of Political Science
google_analytics: [Your Google Analytics tracking ID]
logo: ![kevin](https://opic.osu.edu/simmt.1?aspect=p&width=300)
