theme: jekyll-theme-minimal
title: Kevin Simmt
description: >
  Lecturer <br />
  Department of Political Science <br />
  California Polytechnic <br/ >
  <a href="mailto:ksimmt@calpoly.edu">ksimmt@calpoly.edu</a>
logo: /Simmt.jgp
google_analytics: []
