theme: jekyll-theme-minimal
title: Kevin Simmt
description: >
  PhD Candidate <br />
  Department of Political Science <br />
  The Ohio State University <br/ >
  <a href="mailto:simmt.1@osu.edu">simmt.1@osu.edu</a>
logo: /simmt.JPG
google_analytics: []
